sleep_time: 0.3
device_name: 127.0.0.1:16384
dimensions: 1280,720 # 屏幕分辨率，请注意使用英文逗号

remote_path: /sdcard/screenshot.png # 部分模拟器存储截图的位置不同

# 调试用，没有实际作用
device_name2: 127.0.0.1:16416

# 程序自动配置, 勿动
current_path: C:\Software\DEV\wqmt_assistant
saved_selections: 启动